services:
  web:
    container_name: asana_fastapi
    image: asana_fastapi
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: dev
    ports:
      - 8000:80
    environment:
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      APP_NAME: ${APP_NAME}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRES_MINUTES: ${ACCESS_TOKEN_EXPIRES_MINUTES}
