services:
  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    command: ["poetry", "run", "/start.sh"]
    # volumes:
    #   - .:/app
    ports:
      - 8000:80
    environment:
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      APP_NAME: ${APP_NAME}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRES_MINUTES: ${ACCESS_TOKEN_EXPIRES_MINUTES}
