services:
  web:
    container_name: asana_fastapi
    image: asana_fastapi
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: dev
    volumes:
      - ..:/app
      # linking blank dir in .venv to container .venv to prevent errors
      - ../.venv/dev/null:/app/.venv
    ports:
      - "8000:80"
    env_file: "../.env"
