name: Build, Test, and Deploy Backup

on: [workflow_dispatch]

jobs:
  build_and_test:
    name: Continuous Integration and Delivery
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Build with Cache Action
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          image_tag: latest
          dockerfile: docker/Dockerfile
          image_name: colerutledge/asana_fastapi
          push_image_and_stages: |
            docker run \
              --name asana_fastapi \
              --rm -d -p 8000:8001 \
              ghcr.io/colerutledge/asana_fastapi-stages:3
            docker exec asana_fastapi python -m pytest .

      # - name: Run Container -- Dev/Test
      #   run: |
      #     docker run \
      #     --name asana_fastapi \
      #     --rm -d -p 8000:8001 \
      #     ghcr.io/colerutledge/asana_fastapi-stages:3

      # - name: Pull image from Container Registry
      #   run: docker pull ghcr.io/colerutledge/asana_fastapi:latest

      # - name: Build Image -- Dev/Test
      #   run: |
      #     docker buildx build \
      #     --target dev \
      #     --cache-from ghcr.io/colerutledge/asana_fastapi \
      #     --file ./docker/Dockerfile \
      #     --tag ghcr.io/colerutledge/asana_fastapi_builder:latest \
      #     "."

      # - name: Run Tests and Stop Container
      #   run: docker exec asana_fastapi python -m pytest .

      # - name: Run Linting
      #   run: docker exec asana_fastapi python -m flake8 ./app

      # - name: Stop Container
      #   run: docker stop asana_fastapi

      # - name: Build Image -- Prod
      #   run: |
      #     docker build \
      #     --target prod \
      #     --cache-from ghcr.io/colerutledge/asana_fastapi:latest \
      #     --file ./docker/Dockerfile \
      #     --tag ghcr.io/colerutledge/asana_fastapi:latest \
      #     "."

      # - name: Deploy to Heroku
      # - uses: akhileshns/heroku-deploy@v3.12.12
      #   with:
      #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
      #     heroku_app_name: "asana-fastapi"
      #     heroku_email: "colerutledge@gmail.com"
      #     usedocker: true
      #   env:
      #     HD_ADMIN_EMAIL: "colerutledge@gmail.com"
      #     HD_APP_NAME: "asana_fastapi"
      #     HD_SECRET_KEY: ${{ secrets.SECRET_KEY }}
      #     HD_ALGORITHM: ${{ secrets.ALGORITHM }}
      #     HD_ACCESS_TOKEN_EXPIRES_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRES_MINUTES }}
