name: Container

on: push

jobs:
  pull_and_run:
    name: Login to Github Container Registry
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout master
      #   uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Pull image from Container Registry
        run: docker pull ghcr.io/colerutledge/asana_fastapi:latest
      - name: Run Container
        run: docker run --name asana_fastapi --rm -d -p 8000:8001 ghcr.io/colerutledge/asana_fastapi:latest
      - name: Check Logs
        run: docker logs --tail 1000 -f asana_fastapi
