name: Build, Test, and Deploy

on: [push]

jobs:
  build_and_test:
    name: Continuous Integration and Delivery
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Pull image from Container Registry
        run: docker pull ghcr.io/colerutledge/asana_fastapi:latest

      - name: Build Image -- Dev/Test
        run: |
          docker build \
          --target dev \
          --cache-from ghcr.io/colerutledge/asana_fastapi:latest \
          --file ./docker/Dockerfile \
          --tag ghcr.io/colerutledge/asana_fastapi:latest \
          "."

      - name: Run Container -- Dev/Test
        run: |
          docker run \
          --name asana_fastapi \
          --rm -d -p 8000:8001 \
          ghcr.io/colerutledge/asana_fastapi:latest

      - name: Run Tests
        run: docker exec asana_fastapi python -m pytest .

      - name: Run Linting
        run: docker exec asana_fastapi python -m flake8 ./app

      - name: Stop Container
        run: docker stop asana_fastapi

      - name: Build Image -- Prod
        run: |
          docker build \
          --target prod \
          --cache-from ghcr.io/colerutledge/asana_fastapi:latest \
          --file ./docker/Dockerfile \
          --tag ghcr.io/colerutledge/asana_fastapi:latest \
          "."

      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          file: ./docker/Dockerfile
          target: prod
          push: true
          cache-from: ghcr.io/colerutledge/asana_fastapi:latest
          tags: ghcr.io/colerutledge/asana_fastapi:latest

      # - name: Deploy to Heroku
      # - uses: akhileshns/heroku-deploy@v3.12.12
      #   with:
      #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
      #     heroku_app_name: "asana-fastapi"
      #     heroku_email: "colerutledge@gmail.com"
      #     usedocker: true
      #   env:
      #     HD_ADMIN_EMAIL: "colerutledge@gmail.com"
      #     HD_APP_NAME: "asana_fastapi"
      #     HD_SECRET_KEY: ${{ secrets.SECRET_KEY }}
      #     HD_ALGORITHM: ${{ secrets.ALGORITHM }}
      #     HD_ACCESS_TOKEN_EXPIRES_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRES_MINUTES }}
