name: Continuous Integration and Delivery

on: workflow_dispatch

jobs:
  build:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Push to GitHub Container Registry
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/colerutledge/asana_fastapi:latest

  deploy:
    name: Deploy container to Heroku
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "asana-fastapi"
          heroku_email: "colerutledge@gmail.com"
          usedocker: true
        env:
          HD_ADMIN_EMAIL: "colerutledge@gmail.com"
          HD_APP_NAME: "asana_fastapi"
          HD_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          HD_ALGORITHM: ${{ secrets.ALGORITHM }}
          HD_ACCESS_TOKEN_EXPIRES_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRES_MINUTES }}
