name: Deploy to Heroku

on: workflow_dispatch

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      # - name: Check out the repo
      #   uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Push to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: asana_fastapi:latest

          # username: ${{ github.actor }}
          # password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          # repository: colerutledge/asana_fastapi/asana_fastapi
          # tag_with_ref: true
          # tags: asana_fastapi:latest
        # uses: docker/build-push-action@v1
        # with:
        #   username: ${{ github.actor }}
        #   password: ${{ secrets.GITHUB_TOKEN }}
        #   registry: docker.pkg.github.com
        #   repository: colerutledge/asana_fastapi/asana_fastapi
        #   tag_with_ref: true

  build:
    name: Deploy Docker image to Heroku
    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "asana-fastapi"
          heroku_email: "colerutledge@gmail.com"
          usedocker: true
        env:
          HD_ADMIN_EMAIL: "colerutledge@gmail.com"
          HD_APP_NAME: "asana_fastapi"
          HD_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          HD_ALGORITHM: ${{ secrets.ALGORITHM }}
          HD_ACCESS_TOKEN_EXPIRES_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRES_MINUTES }}
